### ISSUE TITLE
Config file. Purpose of the Bot.

### ISSUE THREAD

**Issue by phillfarrugia** [crisbal/Node-Telegram-Bot#10]
I should preface this issue with, do you see Node-Telegram-Bot as intended to be a single bot that everyone uses? Or like I do, something that anyone can clone and spawn up their own instance for their own Telegram chats?

Currently the config.js file is committed into git therefore every time I change it, git wants to commit the changes. I see the config file as being useful, down the track we'll be able to put more in there for users to customise the bot further.

Not sure what yet, but we need a better solution for preventing config file from being commit into git every time.

**Comment by crisbal** [comment]
As you said I see the bot as "something that anyone can clone and spawn up their own instance for their own Telegram chats". When they introduced the new bot API people began creating public bots which offers a single feature and are very little configurable. 

Before the Bot API, many people used this project as a Bot for their group chats: https://github.com/yagop/telegram-bot

Which works on the same logic as our project: it offers the tools to write plugins and the ability to spawn the bot on a personal machine, with the ability to enable and disable and config every single plugin/command. That project don't use the Bot API but something a bit more primitive and uses lua , which I consider a niche language, not as popular and easy as JS.  

-------

I searched a bit for the configuration file issue and I found this: 
http://stackoverflow.com/questions/4743770/git-collaboration-how-to-manage-configuration-files

The first two solutions suggested by the first answer are interesting and could be used in our case, but this mean that every time we add a line to the "real" config file we also have to remember to  add it to the "example/default" one. 

Also if we plan on using the config file more, is it really necessary to use the ENV varriables for storing API keys? Does it offer any advantage?

**Comment by phillfarrugia** [comment]
Env variables come down to the same problem as having a config checked into the repo.

Users will clone the repo, set the plugins they want, set the tokens for their integrations. Tokens shouldn't be committed into version control. Environment variables are used exactly for this sort of scenario, it allows users to configure the dependencies environment without the need for a code change.
