### ISSUE TITLE
Pretty Console Output + Logger

### ISSUE THREAD

**Issue by phillfarrugia** [crisbal/Node-Telegram-Bot#11]
Suggestion, we could use the npm module 'colors' to make the console output cleaner and a bit fun. 
https://www.npmjs.com/package/colors

Probably when we have a better name for the bot and have worked on it more. At the same time, we should be more strict on exactly what messages we output to the console to prevent it from becoming necessarily noisy.

Don't have to do this now, but adding to the to do list

**Comment by crisbal** [comment]
The best thing is that we should implement some kind of logger which has various levels of logging,  INFO for everything, DEBUG for debugging, etc and based on the logging level that is set only desired messages will be shown. 

Something like this exists in python, will look around If exists for node.

Also we could have a log combined with console output.

**Comment by crisbal** [comment]
Look at this logger: https://github.com/winstonjs/winston

If you are OK I will implement it in the project.

**Comment by phillfarrugia** [comment]
Looks interesting, we should hold off on this until we've improved the core functionality I think
