### ISSUE TITLE
/g command doens't accept special charecters (space, +, possibly others)

### ISSUE THREAD

**Issue by GuapoTaco** [crisbal/Node-Telegram-Bot#16]
the `/g` command has some serious bugs. If you enter the `/g` command with only special characters (I didn't actually test this, just assumed) than it just crashes the bot.

Example:
```
/g +++
```
Crashes the bot.

Also, if there is a special character mixed in, it will mess up the url in the end.

Example:
```
/g C++
```
This doesn't crash the bot, but spits out an invalid link.

**Comment by crisbal** [comment]
Thanks, for the report. I will try to fix this for the next release.

**Comment by crisbal** [comment]
Fixed! It will start working next time I restart the bot
