### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by phillfarrugia** [crisbal/Node-Telegram-Bot#2]
Seems like there's currently no tests implemented. Would probably be a good idea to consider writing a few tests before/if this project gets any larger.

I'm not very opinionated when it comes to JS test frameworks, any suggestions or preferences are welcome?

Also I'm happy to do this when I get time.

**Comment by crisbal** [comment]
Hey,

I never done anything test-related, ever. It is something I always wanted to learn but never had the right inspiration.  

What would you write tests for? The plugins?

I you want to implement them, feel free to choose any test framework you are comfortable with.

Off Topic: do you know where I could share the project to make it more popular? It seems to have the basic things that may get it a few users.

Thanks again, have a good day!

**Comment by phillfarrugia** [comment]
Hey @crisbal !
Ever since telegram implemented an official bots API I've been looking for a flexible javascript implementation that I could play around with and build bots with. One of the hardest things at the moment is deploying a bot that is always on, aside from a local server. I stumbled across this one and it seems to have lots of potential to become a super easy way to start a Bot with a few plugins and throw onto a service like Heroku.

Writing plugins for this look to be ridiculously easy. I have the intention of continuing to contribute to the project and make it better, I hope you don't mind if I do?

Not sure of anywhere to share the project, I believe there are a few telegram bot related directories like [/r/TelegramBots](https://www.reddit.com/r/TelegramBots/). Might be worth throwing a link on to one of them.

In regards to tests, it would be beneficial to write a few test cases for the bot itself. Just to ensure that it is handling errors as expected, forwarding messages to plugins correctly, loading plugins correctly and so forth.

Writing plugins will be easier for contributors if they can be sure the bot itself is working as expected.

**Comment by crisbal** [comment]
Hey,

feel free to do whatever you want in regards of tests.

I didn't  work on the project for a few weeks but now I might pick it up again: there are a few things to handle, update some plugins, improve the code, add some utils methods.... I will work on this in the next days.

If you want to work on it I have no problem: I will be very happy :+1: 

I will post a link later on that subreddit, thanks!

Bye! :wave:
