### ISSUE TITLE
/unset command bug

### ISSUE THREAD

**Issue by AleRao** [crisbal/Node-Telegram-Bot#25]
I am using this (great) bot in a chat. We have set a /set command with two words, separated by a blank space, like "/set word1 word2"
Now we cannot unset the command because the /unset command returns "/unset word1".
We also tried with "/unset <word1 word2>" like suggested with the help. but the return value is "/unset <word1".

Thanks in advance.

**Comment by crisbal** [comment]
Hey. 

Yeah that is a pretty stupid thing  I did not think of. 

Tomorrow morning I will fix it (it is just a one liner thing) and it will be working again. 

If you are really impatient you can fix this now by changing this line in plugins/set.js

var matchUnset = Util.parseCommand(msg.text,["unset"]);

With 


var matchUnset = Util.parseCommand(msg.text,["unset"], { joinParams: true });

And it should work again,  I think.

**Comment by crisbal** [comment]
Wait are you using your own version or @Factotum_Bot?

**Comment by crisbal** [comment]
Fixed for @Factotum_Bot. Will fix the source code tomorrow.

**Comment by AleRao** [comment]
Oh, wow! I did not expect such fast reply.
No, I am using the normal version of the bot.

Thank you so much, I'll let you know if the /unset command will work now

**Comment by AleRao** [comment]
Ok, it's working fine. 
Thank you again.
I'll close the issue.
